
spring:
  application:
    name: order-v2-consumer
  redis:
    host: 192.168.236.130
    port: 6379
    password: 123456
    jedis:
      pool:
        max-active: 20

server:
  port: 7768

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
