
spring:
  application:
    name: shop-demo-config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/xiaoxiaoMaoi/nz1905.git
          search-paths: respo
server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/