
spring:
  application:
    name: regist-service
  datasource:
    url: jdbc:mysql://localhost:3306/qf-v6?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123
  mail:
                            host: smtp.qq.com
                            username: 521017280@qq.com
                            password: lfzdgtmuxtducahb
                            default-encoding: utf-8
  redis:
    host: 192.168.32.131
    port: 6379
    password:
    jedis:
      pool:
        max-active: 20

server:
  port: 8762

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

activeServerUrl: http://localhost:8762/email/active/account/

