#spring:
#  application:
#    name: shop-demo-regist-service
#  datasource:
#    url: jdbc:mysql://localhost:3306/qf-v6?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
#    username: root
#    password: 123
#
#server:
#  port: 8762
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    config:
      uri: http://localhost:8888   # 要连接的配置中心服务的地址
      name: regist-service       # 要获取的配置文件的名称
      label: master             # master分支