spring:
  application:
    name: solr-v2-consumer
  redis:
    host: 192.168.236.130
    port: 6379
    password: 123456
    jedis:
      pool:
        max-active: 20
  cloud:
    loadbalancer:
      retry:
        enabled: true

server:
  port: 7766

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


#设置全局方法的超时时间
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
