
spring:
  application:
    name: back-v3-consumer
  cloud:
      loadbalancer:
        retry:
          enabled: true
#  redis:
#    host: 192.168.236.130
#    port: 6379
#    password: 123456
#    jedis:
#      pool:
#        max-active: 20

server:
  port: 9768

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


hystrix:
  metrics:
    enabled: true
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

fdfs:
  so-timeout: 1500
  connect-timeout: 600
  pool:
    jmx-enabled: false
  thumb-image:
    width: 100
    height: 100
  tracker-list: 192.168.101.101:22122
image:
  server: http://192.168.101.101/