spring:
  application:
    name: shop-demo-shopping-consumer

server:
  port: 8767

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

feign:
  hystrix:
    enabled: true
#spring:
#  cloud:
#    config:
#      uri: http://localhost:8888   # 要连接的配置中心服务的地址
#      name: shopping-consumer       # 要获取的配置文件的名称
#      label: master             # master分支